### ISSUE TITLE
command lion vs docopt.rb

### ISSUE THREAD

**Issue by noraj** [picatz/command_lion#7]
Is it still relevant to use command lion today or https://github.com/docopt/docopt.rb is a more reliable and powerful way?

**Comment by picatz** [comment]
I guess it depends what you want. I don't think there's a correct answer. 

I've used `command_lion` for a _bunch_ of random tools ( many I haven't released ) over the years. I like using it, and will likely support it for a while.

Feel free to use whichever tool you like using!

**Comment by picatz** [comment]
Please feel free to open another issue if you have a problem using this gem. Thanks!
